/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ComandaFacil.view;

import br.com.ComandaFacil.DAO.ClienteDAO;
import br.com.ComandaFacil.DAO.PedidoDAO;
import br.com.ComandaFacil.DAO.ProdutoDAO;
import br.com.ComandaFacil.DAO.RelPedidoProdutoDAO;
import br.com.ComandaFacil.controller.ctrlProduto;
import br.com.ComandaFacil.model.ItemProduto;
import br.com.ComandaFacil.model.Pedido;
import br.com.ComandaFacil.model.Produto;
import br.com.ComandaFacil.model.RelPedidoProduto;
import br.com.ComandaFacil.util.Sessao;
import static br.com.ComandaFacil.util.Sessao.cliente;
import static br.com.ComandaFacil.util.Sessao.relPedidoProduto;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author jhonn
 */
public class JFrmRodizio extends javax.swing.JFrame {

    PedidoDAO pedidoDao = new PedidoDAO();
    ProdutoDAO produtoDao = new ProdutoDAO();
    RelPedidoProdutoDAO relPedidoProdutoDao = new RelPedidoProdutoDAO();
    RelPedidoProduto relPedidoProduto = new RelPedidoProduto();
    ctrlProduto ctrlProduto = new ctrlProduto();
    Pedido pedido = new Pedido();
    Produto produto = new Produto();
    int idPedido = 0;
    int idProduto = 0;
    Vector<Integer> id_prod = new Vector<Integer>();

    /**
     * Creates new form JFrmRodizio
     */
    public JFrmRodizio() {
        initFrmRodizio();
    }

    public JFrmRodizio(String numMesa) {
        //inserirMesa();
        initFrmRodizio();
        jLabelMesa.setText(numMesa);
        this.pedido.setDataPedido(new Date());
        this.pedido.setNumMesa(numMesa);
        this.pedido.setIdCliente(Sessao.idCliente);
    }

    public void initFrmRodizio() {
        initComponents();
        testeConex();
        jLabel1.setText((Sessao.nomeUsuario));
        jLabel2NumeroPedido.setText(String.valueOf(pedidoDao.autPedido().getIdPedido() + 1));
    }

    public void inserirMesa() {
        String numMesa = JOptionPane.showInputDialog(this, "Digite o número da mesa");

        if (numMesa == null) {
            JFrmMenu frmmenu = new JFrmMenu();
            frmmenu.setVisible(true);
            // this.setVisible(false);
            dispose();
        } else {
            while (numMesa.equals("")) {

                if (numMesa.equals("")) {
                    numMesa = JOptionPane.showInputDialog(this, "Digite o número da mesa");
                }
            }

            pedido.setNumMesa(numMesa);
            pedido.setIdCliente((Sessao.idCliente));

            pedido.setDataPedido(new Date());
            jLabelMesa.setText(pedido.getNumMesa());
            jLabel2NumeroPedido.setText(String.valueOf(pedidoDao.autPedido().getIdPedido()));
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButtonAdicionarItem = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        txtQuant = new javax.swing.JTextField();
        jButtonFecharPedido = new javax.swing.JButton();
        jLabel2NumeroPedido = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxItemProdutos = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListProdutos = new javax.swing.JList<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabelMesa = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelCodigo = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(760, 403));
        jPanel1.setPreferredSize(new java.awt.Dimension(760, 403));
        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(185, 0, 0));

        jButtonAdicionarItem.setBackground(new java.awt.Color(254, 254, 254));
        jButtonAdicionarItem.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButtonAdicionarItem.setForeground(new java.awt.Color(185, 0, 0));
        jButtonAdicionarItem.setText("Adicionar item");
        jButtonAdicionarItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarItemActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(185, 0, 0));

        jLabel20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Quantidade:");

        txtQuant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        jButtonFecharPedido.setBackground(new java.awt.Color(254, 254, 254));
        jButtonFecharPedido.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButtonFecharPedido.setForeground(new java.awt.Color(185, 0, 0));
        jButtonFecharPedido.setText("Fechar pedido");
        jButtonFecharPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharPedidoActionPerformed(evt);
            }
        });

        jLabel2NumeroPedido.setForeground(new java.awt.Color(254, 254, 254));

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(254, 254, 254));
        jLabel2.setText("Nº Pedido:");

        jComboBoxItemProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxItemProdutosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2NumeroPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxItemProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonFecharPedido)
                            .addComponent(jButtonAdicionarItem))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2NumeroPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addComponent(jComboBoxItemProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addComponent(jButtonAdicionarItem)
                .addGap(18, 18, 18)
                .addComponent(jButtonFecharPedido)
                .addGap(151, 151, 151))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 240, 330));

        jPanel3.setBackground(new java.awt.Color(185, 0, 0));

        jListProdutos.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jListProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListProdutos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 100, -1, 461));

        jLabel13.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ComandaFacil/Imagem/Comanda facil logo 2.2.png"))); // NOI18N
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, -1, -1));

        jLabel16.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel16.setText("Faça seu pedido!");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 11, -1, -1));

        jPanel4.setBackground(new java.awt.Color(185, 0, 0));

        jLabel18.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Mesa:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 500, -1, -1));

        jLabelMesa.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jPanel1.add(jLabelMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 500, 71, 46));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 95, 27));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jLabel3.setText("Confira seu pedido:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, -1, -1));
        jPanel1.add(jLabelCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        btnVoltar.setBackground(new java.awt.Color(185, 0, 0));
        btnVoltar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(255, 255, 255));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });
        jPanel1.add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel4.setText("para excluir o item clique no nome dele");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 570, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        JFrmMenu frmmenu = new JFrmMenu();
        frmmenu.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    DefaultListModel model = new DefaultListModel();
    private void jListProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListProdutosMouseClicked
        // TODO add your handling code here:
        //chamar método para excluir excluirProdutoComanda 
        relPedidoProdutoDao.excluirProdutoComanda(idPedido, idProduto);

        JOptionPane.showMessageDialog(null, "Item excluido " + jListProdutos.getSelectedValue());

        //model.removeElement(jList1.getSelectedIndex() + " " + txtQuant.getText());
        int index = jListProdutos.getSelectedIndex();
        if (index >= 0) {
            model.removeElementAt(index);
        }

        //  System.out.println(  jList1.getSelectedValue());
    }//GEN-LAST:event_jListProdutosMouseClicked

    private void jComboBoxItemProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxItemProdutosActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jComboBoxItemProdutosActionPerformed

    private void jButtonFecharPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharPedidoActionPerformed
        // TODO add your handling code here:

        try {
            //adicionando idCliente dentro do objeto pedido para que seja salvo corretamente no BD
            pedido.setIdCliente(cliente.getIdCliente());

            //salva o pedido no BD e rotorna para variavel resPedido o pedido com informação do ID
            Pedido resPedido = pedidoDao.fazerPedido(pedido);

            if (resPedido.getIdPedido() != null) {
                pedido.getRelPedidoProduto().forEach((rpp) -> {
                    rpp.setIdPedido(resPedido.getIdPedido());
                    relPedidoProdutoDao.incluirProduto(rpp);
                });
            }

            JOptionPane.showMessageDialog(null, "OPERAÇÃO FECHADA COM SUCESSO.");
            JFrmMenu frmmenu = new JFrmMenu();
            frmmenu.setVisible(true);
            dispose();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro inesperado ao Incluir: " + e.getMessage());
        }
    }//GEN-LAST:event_jButtonFecharPedidoActionPerformed

    private void txtQuantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantActionPerformed

    private void jButtonAdicionarItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarItemActionPerformed
        // TODO add your handling code here:

        if (!jComboBoxItemProdutos.getSelectedItem().toString().equals("")) {

            jListProdutos.setModel(model);
        }

        if (Integer.parseInt(txtQuant.getText()) <= 10) {

            RelPedidoProduto relacionamento = new RelPedidoProduto();

            relacionamento.setIdPedido(pedidoDao.autPedido().getIdPedido());
            relacionamento.setIdProduto(id_prod.get(jComboBoxItemProdutos.getSelectedIndex()));
            relacionamento.setQuantidadeProd(Integer.parseInt(txtQuant.getText()));

            // banco de dados
            //relPedidoProdutoDao.incluirProduto(relacionamento);
            pedido.addRelPedidoProduto(relacionamento);
            model.addElement(jComboBoxItemProdutos.getSelectedItem().toString() + " " + txtQuant.getText());
        } else {
            JOptionPane.showMessageDialog(null, "A quantidade máxima deve ser de 10 unidades!");
        }

        // ArrayList<ItemProduto> produtos = pedido.getProdutos();
        // itemProduto.setIdProduto(jComboBox1.get);    }
    }//GEN-LAST:event_jButtonAdicionarItemActionPerformed

    public void testeConex() {
        try {

            ctrlProduto ctrlProduto = new ctrlProduto();
            jComboBoxItemProdutos.removeAllItems();

            ResultSet rs = ctrlProduto.consultarPedidosCombo();

            while (rs.next()) {
                relPedidoProduto.setIdProduto(rs.getInt("id_prod"));
                id_prod.addElement(rs.getInt("id_prod"));
                jComboBoxItemProdutos.addItem(rs.getString(2));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Carregar produto" + e);

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmRodizio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmRodizio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmRodizio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmRodizio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmRodizio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAdicionarItem;
    private javax.swing.JButton jButtonFecharPedido;
    private javax.swing.JComboBox<String> jComboBoxItemProdutos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel2NumeroPedido;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelCodigo;
    private javax.swing.JLabel jLabelMesa;
    private javax.swing.JList<String> jListProdutos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtQuant;
    // End of variables declaration//GEN-END:variables
}
