/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.ComandaFacil.view;

import br.com.ComandaFacil.model.Pedido;
import br.com.ComandaFacil.util.Sessao;
import java.awt.Color;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author jhonn
 */
public class JFrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form JFrmMenu
     */
    public JFrmMenu() {
        initComponents();
        jLabelnomeUsuario2.setText(Sessao.nomeUsuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButtonVoltar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonParticipar = new javax.swing.JButton();
        jButtonHistorico = new javax.swing.JButton();
        jLabelNomeUsuario = new javax.swing.JLabel();
        jLabelnomeUsuario2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(760, 403));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(185, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 170, -1, -1));

        jButtonVoltar.setBackground(new java.awt.Color(254, 254, 254));
        jButtonVoltar.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jButtonVoltar.setForeground(new java.awt.Color(185, 0, 0));
        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 80, 27));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/ComandaFacil/Imagem/Comanda facil logo.png"))); // NOI18N
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 438));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 36)); // NOI18N
        jLabel2.setText("Bem-vindo(a)");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 49, 250, 58));

        jButtonParticipar.setBackground(new java.awt.Color(185, 0, 0));
        jButtonParticipar.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButtonParticipar.setForeground(new java.awt.Color(255, 250, 250));
        jButtonParticipar.setText("Participar do Rodízio");
        jButtonParticipar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonParticiparActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonParticipar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 216, 47));

        jButtonHistorico.setBackground(new java.awt.Color(185, 0, 0));
        jButtonHistorico.setFont(new java.awt.Font("Ubuntu", 1, 18)); // NOI18N
        jButtonHistorico.setForeground(new java.awt.Color(254, 254, 254));
        jButtonHistorico.setText("Histórico");
        jButtonHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHistoricoActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 215, 47));
        jPanel1.add(jLabelNomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 119, 147, -1));

        jLabelnomeUsuario2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        jLabelnomeUsuario2.setText("jLabel4");
        jPanel1.add(jLabelnomeUsuario2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 240, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void inserirMesa() {
        String numMesa = JOptionPane.showInputDialog(this, "Digite o número da mesa");

        if (numMesa != null) {

            while (numMesa.equals("")) {

                if (numMesa.equals("")) {
                    numMesa = JOptionPane.showInputDialog(this, "Digite o número da mesa");
                }
            }

            JFrmRodizio frmrodizio = new JFrmRodizio(numMesa);
            frmrodizio.setVisible(true);
            dispose();
        }

    }
    private void jButtonParticiparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonParticiparActionPerformed

       /* JFrmRodizio frmrodizio = new JFrmRodizio();
        frmrodizio.setVisible(true);
        dispose();*/
       inserirMesa();
    }//GEN-LAST:event_jButtonParticiparActionPerformed

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        JFrmTelaInicial frmtelainicial = new JFrmTelaInicial();
        frmtelainicial.setVisible(true);
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jButtonHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHistoricoActionPerformed
        JFrmHistorico jfrmHistorico = new JFrmHistorico();
        jfrmHistorico.setVisible(true);
        dispose();

// TODO add your handling code here:
    }//GEN-LAST:event_jButtonHistoricoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHistorico;
    private javax.swing.JButton jButtonParticipar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelNomeUsuario;
    private javax.swing.JLabel jLabelnomeUsuario2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
